services:
  - type: web
    name: idv-drive-upload
    env: docker
    rootDir: idv-backend
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: MAX_UPLOAD_BYTES
        value: "52428800"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: CLOUDINARY_CLOUD_NAME
        value: ""
      - key: CLOUDINARY_API_KEY
        value: ""
      - key: CLOUDINARY_API_SECRET
        value: ""
      - key: CLOUDINARY_FOLDER
        value: "id-uploads"
      - key: CLOUDINARY_FILENAME_PREFIX
        value: "id-upload"
